[package]
name = "numbers-log"
version = "0.1.0"
authors = ["Carlos Roman <carlos@cliche-corp.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
